# TCL File Generated by Component Editor 17.1
# Fri Sep 08 16:44:21 MST 2017
# DO NOT MODIFY


# 
# avalon_st_mm_flasher "Avalon ST MM Flasher" v1.0
# Steve 2017.09.08.16:44:21
# A custom component that bridges between an Avalon streaming and Avalon  memory-mapped interface and connects to board LEDs to light them based off of System Console dashboard
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_st_mm_flasher
# 
set_module_property DESCRIPTION "A custom component that bridges between an Avalon streaming and Avalon  memory-mapped interface and connects to board LEDs to light them based off of System Console dashboard"
set_module_property NAME avalon_st_mm_flasher
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Training
set_module_property AUTHOR Steve
set_module_property DISPLAY_NAME "Avalon ST MM Flasher"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_st_mm_led
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_st_mm_led.v VERILOG PATH ip/avalon_st_mm_led/avalon_st_mm_led.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter COUNT_MAX STD_LOGIC_VECTOR 83886079
set_parameter_property COUNT_MAX DEFAULT_VALUE 83886079
set_parameter_property COUNT_MAX DISPLAY_NAME COUNT_MAX
set_parameter_property COUNT_MAX WIDTH 34
set_parameter_property COUNT_MAX TYPE STD_LOGIC_VECTOR
set_parameter_property COUNT_MAX ENABLED false
set_parameter_property COUNT_MAX UNITS None
set_parameter_property COUNT_MAX ALLOWED_RANGES 0:17179869183
set_parameter_property COUNT_MAX HDL_PARAMETER true
add_parameter GREEN_WIDTH INTEGER 8 ""
set_parameter_property GREEN_WIDTH DEFAULT_VALUE 8
set_parameter_property GREEN_WIDTH DISPLAY_NAME GREEN_WIDTH
set_parameter_property GREEN_WIDTH WIDTH ""
set_parameter_property GREEN_WIDTH TYPE INTEGER
set_parameter_property GREEN_WIDTH UNITS None
set_parameter_property GREEN_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property GREEN_WIDTH DESCRIPTION ""
set_parameter_property GREEN_WIDTH HDL_PARAMETER true
add_parameter RED_WIDTH INTEGER 8
set_parameter_property RED_WIDTH DEFAULT_VALUE 8
set_parameter_property RED_WIDTH DISPLAY_NAME RED_WIDTH
set_parameter_property RED_WIDTH TYPE INTEGER
set_parameter_property RED_WIDTH UNITS None
set_parameter_property RED_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RED_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point led
# 
add_interface led avalon end
set_interface_property led addressUnits WORDS
set_interface_property led associatedClock clock
set_interface_property led associatedReset reset
set_interface_property led bitsPerSymbol 8
set_interface_property led burstOnBurstBoundariesOnly false
set_interface_property led burstcountUnits WORDS
set_interface_property led explicitAddressSpan 0
set_interface_property led holdTime 0
set_interface_property led linewrapBursts false
set_interface_property led maximumPendingReadTransactions 0
set_interface_property led maximumPendingWriteTransactions 0
set_interface_property led readLatency 0
set_interface_property led readWaitTime 1
set_interface_property led setupTime 0
set_interface_property led timingUnits Cycles
set_interface_property led writeWaitTime 0
set_interface_property led ENABLED true
set_interface_property led EXPORT_OF ""
set_interface_property led PORT_NAME_MAP ""
set_interface_property led CMSIS_SVD_VARIABLES ""
set_interface_property led SVD_ADDRESS_GROUP ""

add_interface_port led avs_led_writedata writedata Input 32
add_interface_port led avs_led_address address Input 2
add_interface_port led avs_led_readdata readdata Output 32
add_interface_port led avs_led_write write Input 1
add_interface_port led avs_led_read read Input 1
set_interface_assignment led embeddedsw.configuration.isFlash 0
set_interface_assignment led embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment led embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment led embeddedsw.configuration.isPrintableDevice 0


# 
# connection point swpb
# 
add_interface swpb avalon start
set_interface_property swpb addressUnits SYMBOLS
set_interface_property swpb associatedClock clock
set_interface_property swpb associatedReset reset
set_interface_property swpb bitsPerSymbol 8
set_interface_property swpb burstOnBurstBoundariesOnly false
set_interface_property swpb burstcountUnits WORDS
set_interface_property swpb doStreamReads false
set_interface_property swpb doStreamWrites false
set_interface_property swpb holdTime 0
set_interface_property swpb linewrapBursts false
set_interface_property swpb maximumPendingReadTransactions 0
set_interface_property swpb maximumPendingWriteTransactions 0
set_interface_property swpb readLatency 0
set_interface_property swpb readWaitTime 1
set_interface_property swpb setupTime 0
set_interface_property swpb timingUnits Cycles
set_interface_property swpb writeWaitTime 0
set_interface_property swpb ENABLED true
set_interface_property swpb EXPORT_OF ""
set_interface_property swpb PORT_NAME_MAP ""
set_interface_property swpb CMSIS_SVD_VARIABLES ""
set_interface_property swpb SVD_ADDRESS_GROUP ""

add_interface_port swpb avm_swpb_address address Output 32
add_interface_port swpb avm_swpb_readdata readdata Input 32
add_interface_port swpb avm_swpb_waitrequest waitrequest Input 1
add_interface_port swpb avm_swpb_read_n read_n Output 1


# 
# connection point ledfifo
# 
add_interface ledfifo avalon_streaming end
set_interface_property ledfifo associatedClock clock
set_interface_property ledfifo associatedReset reset
set_interface_property ledfifo dataBitsPerSymbol 32
set_interface_property ledfifo errorDescriptor ""
set_interface_property ledfifo firstSymbolInHighOrderBits true
set_interface_property ledfifo maxChannel 0
set_interface_property ledfifo readyLatency 0
set_interface_property ledfifo ENABLED true
set_interface_property ledfifo EXPORT_OF ""
set_interface_property ledfifo PORT_NAME_MAP ""
set_interface_property ledfifo CMSIS_SVD_VARIABLES ""
set_interface_property ledfifo SVD_ADDRESS_GROUP ""

add_interface_port ledfifo asi_ledfifo_valid valid Input 1
add_interface_port ledfifo asi_ledfifo_data data Input 32
add_interface_port ledfifo asi_ledfifo_ready ready Output 1


# 
# connection point greenled_out
# 
add_interface greenled_out conduit end
set_interface_property greenled_out associatedClock clock
set_interface_property greenled_out associatedReset ""
set_interface_property greenled_out ENABLED true
set_interface_property greenled_out EXPORT_OF ""
set_interface_property greenled_out PORT_NAME_MAP ""
set_interface_property greenled_out CMSIS_SVD_VARIABLES ""
set_interface_property greenled_out SVD_ADDRESS_GROUP ""

add_interface_port greenled_out coe_greenled_out export Output GREEN_WIDTH


# 
# connection point hex0_out
# 
add_interface hex0_out conduit end
set_interface_property hex0_out associatedClock clock
set_interface_property hex0_out associatedReset ""
set_interface_property hex0_out ENABLED true
set_interface_property hex0_out EXPORT_OF ""
set_interface_property hex0_out PORT_NAME_MAP ""
set_interface_property hex0_out CMSIS_SVD_VARIABLES ""
set_interface_property hex0_out SVD_ADDRESS_GROUP ""

add_interface_port hex0_out coe_hex0_out export Output 7


# 
# connection point redled_out
# 
add_interface redled_out conduit end
set_interface_property redled_out associatedClock clock
set_interface_property redled_out associatedReset ""
set_interface_property redled_out ENABLED true
set_interface_property redled_out EXPORT_OF ""
set_interface_property redled_out PORT_NAME_MAP ""
set_interface_property redled_out CMSIS_SVD_VARIABLES ""
set_interface_property redled_out SVD_ADDRESS_GROUP ""

add_interface_port redled_out coe_redled_out export Output RED_WIDTH


# 
# connection point hex1_out
# 
add_interface hex1_out conduit end
set_interface_property hex1_out associatedClock clock
set_interface_property hex1_out associatedReset ""
set_interface_property hex1_out ENABLED true
set_interface_property hex1_out EXPORT_OF ""
set_interface_property hex1_out PORT_NAME_MAP ""
set_interface_property hex1_out CMSIS_SVD_VARIABLES ""
set_interface_property hex1_out SVD_ADDRESS_GROUP ""

add_interface_port hex1_out coe_hex1_out export Output 7


# 
# connection point hex2_out
# 
add_interface hex2_out conduit end
set_interface_property hex2_out associatedClock clock
set_interface_property hex2_out associatedReset ""
set_interface_property hex2_out ENABLED true
set_interface_property hex2_out EXPORT_OF ""
set_interface_property hex2_out PORT_NAME_MAP ""
set_interface_property hex2_out CMSIS_SVD_VARIABLES ""
set_interface_property hex2_out SVD_ADDRESS_GROUP ""

add_interface_port hex2_out coe_hex2_out export Output 7


# 
# connection point hex3_out
# 
add_interface hex3_out conduit end
set_interface_property hex3_out associatedClock clock
set_interface_property hex3_out associatedReset ""
set_interface_property hex3_out ENABLED true
set_interface_property hex3_out EXPORT_OF ""
set_interface_property hex3_out PORT_NAME_MAP ""
set_interface_property hex3_out CMSIS_SVD_VARIABLES ""
set_interface_property hex3_out SVD_ADDRESS_GROUP ""

add_interface_port hex3_out coe_hex3_out export Output 7

