# TCL File Generated by Component Editor 17.1
# Sun Sep 10 16:02:37 MST 2017
# DO NOT MODIFY


# 
# button_switch_pio "Button Switch PIO" v1.0
#  2017.09.10.16:02:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module button_switch_pio
# 
set_module_property DESCRIPTION ""
set_module_property NAME button_switch_pio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Training
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Button Switch PIO"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL button_switch_pio
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file button_switch_pio.v VERILOG PATH ip/button_switch_pio/button_switch_pio.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter BUTTON_WIDTH INTEGER 4
set_parameter_property BUTTON_WIDTH DEFAULT_VALUE 4
set_parameter_property BUTTON_WIDTH DISPLAY_NAME BUTTON_WIDTH
set_parameter_property BUTTON_WIDTH TYPE INTEGER
set_parameter_property BUTTON_WIDTH UNITS None
set_parameter_property BUTTON_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BUTTON_WIDTH HDL_PARAMETER true
add_parameter SWITCH_WIDTH INTEGER 8
set_parameter_property SWITCH_WIDTH DEFAULT_VALUE 8
set_parameter_property SWITCH_WIDTH DISPLAY_NAME SWITCH_WIDTH
set_parameter_property SWITCH_WIDTH TYPE INTEGER
set_parameter_property SWITCH_WIDTH UNITS None
set_parameter_property SWITCH_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SWITCH_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point buttonreg
# 
add_interface buttonreg avalon end
set_interface_property buttonreg addressUnits WORDS
set_interface_property buttonreg associatedClock clock
set_interface_property buttonreg associatedReset reset
set_interface_property buttonreg bitsPerSymbol 8
set_interface_property buttonreg burstOnBurstBoundariesOnly false
set_interface_property buttonreg burstcountUnits WORDS
set_interface_property buttonreg explicitAddressSpan 0
set_interface_property buttonreg holdTime 0
set_interface_property buttonreg linewrapBursts false
set_interface_property buttonreg maximumPendingReadTransactions 0
set_interface_property buttonreg maximumPendingWriteTransactions 0
set_interface_property buttonreg readLatency 0
set_interface_property buttonreg readWaitTime 1
set_interface_property buttonreg setupTime 0
set_interface_property buttonreg timingUnits Cycles
set_interface_property buttonreg writeWaitTime 0
set_interface_property buttonreg ENABLED true
set_interface_property buttonreg EXPORT_OF ""
set_interface_property buttonreg PORT_NAME_MAP ""
set_interface_property buttonreg CMSIS_SVD_VARIABLES ""
set_interface_property buttonreg SVD_ADDRESS_GROUP ""

add_interface_port buttonreg avs_buttonreg_address address Input 2
add_interface_port buttonreg avs_buttonreg_writedata writedata Input 32
add_interface_port buttonreg avs_buttonreg_readdata readdata Output 32
add_interface_port buttonreg avs_buttonreg_write write Input 1
add_interface_port buttonreg avs_buttonreg_read read Input 1
set_interface_assignment buttonreg embeddedsw.configuration.isFlash 0
set_interface_assignment buttonreg embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment buttonreg embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment buttonreg embeddedsw.configuration.isPrintableDevice 0


# 
# connection point button_conduit
# 
add_interface button_conduit conduit end
set_interface_property button_conduit associatedClock clock
set_interface_property button_conduit associatedReset ""
set_interface_property button_conduit ENABLED true
set_interface_property button_conduit EXPORT_OF ""
set_interface_property button_conduit PORT_NAME_MAP ""
set_interface_property button_conduit CMSIS_SVD_VARIABLES ""
set_interface_property button_conduit SVD_ADDRESS_GROUP ""

add_interface_port button_conduit coe_buttons_in export Input BUTTON_WIDTH


# 
# connection point switch_conduit
# 
add_interface switch_conduit conduit end
set_interface_property switch_conduit associatedClock clock
set_interface_property switch_conduit associatedReset ""
set_interface_property switch_conduit ENABLED true
set_interface_property switch_conduit EXPORT_OF ""
set_interface_property switch_conduit PORT_NAME_MAP ""
set_interface_property switch_conduit CMSIS_SVD_VARIABLES ""
set_interface_property switch_conduit SVD_ADDRESS_GROUP ""

add_interface_port switch_conduit coe_switches_in export Input SWITCH_WIDTH

