# TCL File Generated by Component Editor 17.1
# Wed Sep 06 15:03:58 MST 2017
# DO NOT MODIFY


# 
# reset_debounce "Reset Button Debounce" v1.0
# Steve 2017.09.06.15:03:58
# A simply component for debouncing a board pushbutton
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module reset_debounce
# 
set_module_property DESCRIPTION "A simply component for debouncing a board pushbutton"
set_module_property NAME reset_debounce
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Training
set_module_property AUTHOR Steve
set_module_property DISPLAY_NAME "Reset Button Debounce"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL button_debounce
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file button_debounce.v VERILOG PATH ip/button_debounce/button_debounce.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clock_clk clk Input 1


# 
# connection point button_debounce_in
# 
add_interface button_debounce_in reset end
set_interface_property button_debounce_in associatedClock clock
set_interface_property button_debounce_in synchronousEdges NONE
set_interface_property button_debounce_in ENABLED true
set_interface_property button_debounce_in EXPORT_OF ""
set_interface_property button_debounce_in PORT_NAME_MAP ""
set_interface_property button_debounce_in CMSIS_SVD_VARIABLES ""
set_interface_property button_debounce_in SVD_ADDRESS_GROUP ""

add_interface_port button_debounce_in coe_button_in reset_n Input 1


# 
# connection point button_qual
# 
add_interface button_qual reset start
set_interface_property button_qual associatedClock clock
set_interface_property button_qual associatedDirectReset ""
set_interface_property button_qual associatedResetSinks ""
set_interface_property button_qual synchronousEdges DEASSERT
set_interface_property button_qual ENABLED true
set_interface_property button_qual EXPORT_OF ""
set_interface_property button_qual PORT_NAME_MAP ""
set_interface_property button_qual CMSIS_SVD_VARIABLES ""
set_interface_property button_qual SVD_ADDRESS_GROUP ""

add_interface_port button_qual button_qual reset Output 1


# 
# connection point button_qual_n
# 
add_interface button_qual_n reset start
set_interface_property button_qual_n associatedClock clock
set_interface_property button_qual_n associatedDirectReset ""
set_interface_property button_qual_n associatedResetSinks ""
set_interface_property button_qual_n synchronousEdges DEASSERT
set_interface_property button_qual_n ENABLED true
set_interface_property button_qual_n EXPORT_OF ""
set_interface_property button_qual_n PORT_NAME_MAP ""
set_interface_property button_qual_n CMSIS_SVD_VARIABLES ""
set_interface_property button_qual_n SVD_ADDRESS_GROUP ""

add_interface_port button_qual_n button_qual_n reset_n Output 1

